.circleci/config.yml

Uploaded a test dataset to osf (https://osf.io/8k95s/) with one subject and 2 sessions from the Traveling Human Phantom. It is single shell and without reverse phase encoding. One session is Siemens and the other one Philips. The --anat-only pipeline was run locally and the freesurfer derivatives were uploaded as well. The get_data part from config.yml was mirrored from fmriprep, so that it uses this dataset and the cached freesurfer files in the tests.

ENH: add config for circleci

---

.travis.yml
README.rst
setup.cfg

Although this doesn't implement #16, it addresses the need for checking code style before merging in changes. This PR is not meant as an alternative to Black, but rather as an easy first step towards more comprehensive linting, while offloading the contributors from setting up anything on their end.

CI: Add TravisCI for code linting with ``flake8``

---

CONTRIBUTING.md

To be discussed in tomorrow's telecon (Close #12)
There are some descriptions I'll be working on today and tomorrow
morning before finishing the proposal.
This is related (sideways) to #7 too.

MAINT: Add a base of CONTRIBUTING guidelines

---

.maintenance/update_changes.sh
CHANGES.rst

* Adds ``.maintenance/update_changes.sh``, which should be executed before release as:
```
bash .maintenance/update_changes.sh 0.2.1
```
(version 0.2.1 should be replaced by the actual version to be released).
* Update `CHANGES.rst` to represent reality.

MAINT: Add maintenance script to update the changelog, update CHANGES

---

.circleci/config.yml
dmriprep/cli/run.py

MAINT: Revise execution options in CircleCi

---

.travis.yml
dmriprep/conftest.py
dmriprep/interfaces/vectors.py
dmriprep/utils/tests/test_vectors.py
dmriprep/utils/vectors.py
setup.cfg

Per Issue #24 
FR: Conformity check of bvecs and bvals (pure-python implementation)
1) reportlet viz and description of sampling scheme.
2) Parameterized smoke tests for each type of corrupted or incompatible bvec/bval file.
Comments/Suggestions welcome.
@dPys

[ENH] Vector-checking utilities

---

Dockerfile
Makefile

Can't replicate the FOO necessity ??
The version wasn't correctly generated by ``make docker``

FIX: Version on docker target of ``Makefile``

---

dmriprep/cli/run.py
docs/usage.rst

Adds some documentation about our use of popylar.

DOC: Document the fact that we are using popylar/GA for usage tracking.

---

LICENSE

This PR updates the copyright holder and year in the LICENSE file.
See also [PR #13 on dmriprep-viewer](https://github.com/nipreps/dmriprep-viewer/pull/13).

[DOC] Add nipreps developers and year to LICENSE file

---

dmriprep/cli/run.py
dmriprep/workflows/base.py
docs/requirements.txt
setup.cfg

Revise #83 and fix the two outstanding issues:

MAINT: Revisions after previous maintenance commit (#83)

---

dmriprep/utils/vectors.py

We raised a ValueError whenever the number of b-vals and all-zero b-vecs
didn't match. Few lines later, we would overwrite nonzero b-vecs to
match the b-vals, but that step was never reached. This PR allows the
function to just throw a warning instead.
Resolves: #82

ENH: Do not raise error in all instances of b-vecs/vals inconsistencies

---

dmriprep/interfaces/images.py
dmriprep/utils/images.py

This PR:
Future lines
------------
We should think about dropping FSL MCFLIRT, which is used for HMC of the *b = 0* volumes.
Resolves: #90

FIX: Minor refactor of DWI/brainmasks utilities and dtypes

---

dmriprep/interfaces/vectors.py
dmriprep/utils/tests/test_vectors.py
dmriprep/utils/vectors.py
setup.cfg

This PR completes a previous one regarding the diffusion table.
Amends: #100

FIX: Revise vector tests broken when addressing other issues

---

.circleci/config.yml
dmriprep/cli/parser.py
dmriprep/cli/run.py
dmriprep/config/__init__.py
dmriprep/workflows/base.py
setup.cfg

Uses poldracklab/smriprep#107 to skip precalculated anatomical
derivatives, just setting the ``--anat-derivatives <path>`` command line
argument.

ENH: Port the new *anatomical fast-track* from *fMRIPrep*

---

MANIFEST.in
dmriprep/cli/run.py
dmriprep/cli/workflow.py
dmriprep/config/reports-spec.yml
dmriprep/workflows/base.py
dmriprep/workflows/dwi/base.py
dmriprep/workflows/dwi/outputs.py
docs/requirements.txt
pyproject.toml
setup.cfg
setup.py

This PR integrates the new API that will be released with 1.2.0.
References: nipreps/niworkflows#507

ENH: Use new ``DerivativesDataSink`` from NiWorkflows 1.2.0

---

.github/workflows/pythonpackage.yml
Dockerfile
setup.cfg

Dropping Python 3.6 follows suit with Numpy 1.20 and, in principle, *dMRIPrep* will
continue to follow their python support schedule.
Resolves: #145.

FIX/MAINT: Drop Python 3.6 + Revise Python environment (versions pinned) in Dockerfile

---

docs/roadmap.rst

DOC: Revise *dMRIPrep*'s road-map

---

.circleci/config.yml
dmriprep/cli/parser.py
dmriprep/config/reports-spec.yml
dmriprep/interfaces/vectors.py
dmriprep/workflows/base.py
docs/requirements.txt
setup.cfg

Currently, this is blocked by the absence of a general solution to the
reference generation issue (see nipreps/niworkflows#601).
Once adequate DWI references are connected to the estimation workflow,
this feature should work out.
We can test the new feature with ds000206.
Resolves: #111.

ENH: *fieldmap-less* integration from *SDCFlows* 2.0

---

dmriprep/workflows/dwi/eddy.py

If re-running the pipeline, BIDS validation fails because the index and acquisition parameter files are not BIDS-valid.

FIX: Output eddy parameter files to work dir instead of input dir

---

dmriprep/cli/parser.py

That typo was leading to the error 
`AttributeError: type object 'nipype' has no attribute 'omp_nthread'`

FIX: typo in omp_threads

---

docs/conf.py

Fix non-standard `napoleon` custom section mapping:
- Map `Inputs` and `Outputs` to `params_style` and `returns_style`, respectively, instead of mapping them to `Parameters`.
- Map `Mandatory Inputs` and `Optional Inputs` to `params_style`, instead of mapping them to `Parameters`.
- Add the `numpydoc` extension and set the `numpy_doc_show_class_members` and `autodoc_typehints` flags so that the `Attributes` docstrings are shown.
- Map the `Attributes` section to the `Attributes` string in order to show that value instead of `Variables` in the corresponding documentation section.
Documentation:
https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#confval-napoleon_custom_sections https://stackoverflow.com/questions/72220924/sphinx-how-to-show-attributes-as-in-scipy

DOC: Fix non-standard `napoleon` custom section mapping
